import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import AboutUs from '../components/AboutUs';
import Footer from '../components/Footer';
import Gallery from '../components/Gallery/Gallery';
import Header from '../components/Header/Header';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Frontend Mentor | Loopstudios landing page</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Box>
                <Header />
                <AboutUs />
                <Gallery />
                <Footer />
            </Box>
        </div>
    );
}
